services:
  php:
    container_name: php-test
    build:
      context: .
      dockerfile: ./build/php/Dockerfile
      target: php_base
    restart: unless-stopped
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www
    networks:
      - test-network


  nginx:
    build:
      context: .
      dockerfile: ./build/nginx/Dockerfile
      target: nginx_base
    restart: unless-stopped
    depends_on:
      - php
    volumes:
      - ./app/public:/var/www/app/public:ro
      - ./build/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8080:80'
    networks:
      - test-network

networks:
  test-network:
    external: false